### ISSUE TITLE
ERROR  获取用户ActionTicket失败，正在重试

### ISSUE THREAD

**Issue by EchoRR** [Ljzd-PRO/Mys_Goods_Tool#11]
2022-05-07 19:39:39  INFO  正在获取用户ActionTicket
2022-05-07 19:39:39  ERROR  Traceback (most recent call last):
  File "main.py", line 192, in __init__
    actionTicket = json.loads(
TypeError: 'NoneType' object is not subscriptable

2022-05-07 19:44:22  ERROR  获取用户ActionTicket失败，正在重试  
2022-05-07 19:44:22  INFO  正在获取用户ActionTicket  
2022-05-07 19:44:22  ERROR  Traceback (most recent call last):
  File "main.py", line 192, in __init__
TypeError: 'NoneType' object is not subscriptable
换实物时提示这个，大佬救一下😭

**Comment by Ljzd-PRO** [comment]
config.ini中`stoken`有填写吗？出现这个问题是获取`ActionTicket`时得到了错误的返回。原因除了缺少`stoken`或者`stoken`不正确，还有可能是系统时间不准确，因为获取`ActionTicket`时需要发送`DS`，`DS`的生成需要用到当前时间

**Comment by EchoRR** [comment]
> config.ini中`stoken`有填写吗？出现这个问题是获取`ActionTicket`时得到了错误的返回。原因除了缺少`stoken`或者`stoken`不正确，还有可能是系统时间不准确，因为获取`ActionTicket`时需要发送`DS`，`DS`的生成需要用到当前时间

没填stoken，我填下试试

**Comment by EchoRR** [comment]
填了之后可以了，感谢大佬😋

**Comment by hanserband** [comment]
> > config.ini中有填写吗？出现这个问题是获取时得到了错误的返回。原因除了缺少或者不正确，还有可能是系统时间不准确，因为获取时需要发送，的生成需要用到当前时间`stoken``ActionTicket``stoken``stoken``ActionTicket``DS``DS`
> 
> 没填stoken，我填下请问stoken怎么找啊
