### ISSUE TITLE
这次出现了新的报错信息，“不在商品可兑换时间”。5个线程，前2个还有返回信息，后3个感觉像是程序级别的报错信息。

### ISSUE THREAD

**Issue by pbxs666** [Ljzd-PRO/Mys_Goods_Tool#125]
使用最新2.0.5 dev

最近几周，抢了好多次了，之前都是空信息 {"data":null,"message":"","retcode":1028}。
这次终于有返回信息了，结果是兑换时间的问题，{"data":null,"message":"兑换失败，不在商品可兑换时间中","retcode":-2106}。
这个之前有issues提到过可能是本地系统时间导致的，那后3个线程的报错我是真没搞懂。

06-23 18:00:00 [INFO] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 136508784 商品 2023052611696 兑换失败，可以自行确认。
06-23 18:00:00 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"兑换失败，不在商品可兑换时间中","retcode":-2106}
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 136508784 - 【崩坏：星穹铁道】鼠标垫-星旅一瞬 - 线程 5 - 兑换失败
06-23 18:00:00 [INFO] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 136508784 商品 2023052611696 兑换失败，可以自行确认。
06-23 18:00:00 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"兑换失败，不在商品可兑换时间中","retcode":-2106}
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 136508784 - 【崩坏：星穹铁道】鼠标垫-星旅一瞬 - 线程 3 - 兑换失败
06-23 18:00:00 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 136508784 商品 2023052611696 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1269, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 接收兑换结果失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 64, in run

  File "concurrent\futures\_base.py", line 550, in set_result

  File "concurrent\futures\_base.py", line 340, in _invoke_callbacks

  File "apscheduler\executors\pool.py", line 25, in callback

  File "apscheduler\executors\base.py", line 90, in _run_job_success

  File "apscheduler\schedulers\base.py", line 835, in _dispatch_event

> File "mys_goods_tool\exchange_mode.py", line 304, in on_executed

StopIteration
06-23 18:00:00 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 136508784 商品 2023052611696 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1269, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:00 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 136508784 商品 2023052611696 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1269, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 接收兑换结果失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 64, in run

  File "concurrent\futures\_base.py", line 550, in set_result

  File "concurrent\futures\_base.py", line 340, in _invoke_callbacks

  File "apscheduler\executors\pool.py", line 25, in callback

  File "apscheduler\executors\base.py", line 90, in _run_job_success

  File "apscheduler\schedulers\base.py", line 835, in _dispatch_event

> File "mys_goods_tool\exchange_mode.py", line 304, in on_executed

StopIteration
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 接收兑换结果失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 64, in run

  File "concurrent\futures\_base.py", line 550, in set_result

  File "concurrent\futures\_base.py", line 340, in _invoke_callbacks

  File "apscheduler\executors\pool.py", line 25, in callback

  File "apscheduler\executors\base.py", line 90, in _run_job_success

  File "apscheduler\schedulers\base.py", line 835, in _dispatch_event

> File "mys_goods_tool\exchange_mode.py", line 304, in on_executed

StopIteration

**Comment by Ljzd-PRO** [comment]
一般可能是程序从返回的JSON里提取数据，因为格式不符合预期没提取到导致的。可以看看日志文件有没有更多信息

**Comment by pbxs666** [comment]
> 一般可能是程序从返回的JSON里提取数据，因为格式不符合预期没提取到导致的。可以看看日志文件有没有更多信息

没有了，这就是全部的报错信息了。

**Comment by ytgo** [comment]
我的还是返回这个
网络请求返回: {"data":null,"message":"","retcode":1028}

**Comment by pbxs666** [comment]
> 我的还是返回这个 网络请求返回: {"data":null,"message":"","retcode":1028}

星铁的和原神的可能不一样

**Comment by HorizenX1** [comment]
我的也是这样

06-23 11:32:33 [INFO] mys_goods_tool.exchange_mode | 已添加定时兑换任务 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 2023-06-23 18:00:00
06-23 18:00:00 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:00 [INFO] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 兑换失败，可以自行确认。
06-23 18:00:00 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:00 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:00 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"兑换失败，不在商品可兑换时间中","retcode":-2106}
06-23 18:00:00 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 15 - 兑换失败
06-23 18:00:00 [INFO] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 兑换失败，可以自行确认。
06-23 18:00:00 [INFO] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 兑换失败，可以自行确认。
06-23 18:00:00 [INFO] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 兑换失败，可以自行确认。
06-23 18:00:00 [INFO] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 兑换失败，可以自行确认。
06-23 18:00:00 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"兑换失败，不在商品可兑换时间中","retcode":-2106}
06-23 18:00:00 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"兑换失败，不在商品可兑换时间中","retcode":-2106}
06-23 18:00:00 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"兑换失败，不在商品可兑换时间中","retcode":-2106}
06-23 18:00:00 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"兑换失败，不在商品可兑换时间中","retcode":-2106}
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 17 - 兑换失败
06-23 18:00:00 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 10 - 兑换失败
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 12 - 兑换失败
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 18 - 兑换失败
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 11 - 兑换失败
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 13 - 兑换失败
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 16 - 兑换失败
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 1 - 兑换失败
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 14 - 兑换失败
06-23 18:00:00 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 19 - 兑换失败
06-23 18:00:00 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 2 - 兑换失败
06-23 18:00:00 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:00 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:00 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:00 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:01 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:01 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 23 - 兑换失败
06-23 18:00:01 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 24 - 兑换失败
06-23 18:00:01 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 21 - 兑换失败
06-23 18:00:01 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 20 - 兑换失败
06-23 18:00:01 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 22 - 兑换失败
06-23 18:00:01 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:01 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:01 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:01 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 26 - 兑换失败
06-23 18:00:01 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 27 - 兑换失败
06-23 18:00:01 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 25 - 兑换失败
06-23 18:00:01 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:01 [ERROR] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 8973668 商品 2023052611471 请求失败
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 101, in exchange_begin

> File "mys_goods_tool\api.py", line 1260, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
06-23 18:00:01 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 28 - 兑换失败
06-23 18:00:01 [ERROR] mys_goods_tool.exchange_mode | 用户 8973668 - 【崩坏：星穹铁道】光锥系列 亚克力流沙立牌-于夜色中 - 线程 29 - 兑换失败

**Comment by Ljzd-PRO** [comment]
又尝试修复了一下，可以试一下：https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/5479310149

解决了几个可能的问题：
- `device_config`, `salt_config` 如果程序默认值更新了但是用户数据文件用的还是旧的，旧的配置还是会覆盖掉默认值的问题
- 兑换请求的Headers里增加`Referer`，修改`Origin`, `Content-Type`
- Headers的`User-Agent`里的App版本号部分和`x-rpc-app_version`不一致的问题

除了Headers里没有`x-rpc-verify_key`, `x-rpc-device_fp`，其他应该都和米游社App里实际发出的请求一致了。

**Comment by Ljzd-PRO** [comment]
新的一个pre-release：https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/tag/v2.1.0-beta.1
感觉这次兑换成功的概率会高一些。
