### ISSUE TITLE
登录报错“网络连接失败”

### ISSUE THREAD

**Issue by gggssepgf** [Ljzd-PRO/Mys_Goods_Tool#127]
验证码是收到了的，但是填好验证码登录之后就这样报错，
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/48855391/98863e3e-68af-4c33-b789-308889b35c31)
下面是log：

06-26 17:13:30 [INFO] mys_goods_tool.login_view | 已收到Geetest验证结果数据，将发送验证码至 
06-26 17:13:30 [INFO] mys_goods_tool.login_view | 短信验证码已发送至 
06-26 17:13:31 [INFO] mys_goods_tool.geetest | HTTP服务器 - 运行于 ('127.0.0.1', 16749) 的服务器已停止
06-26 17:13:47 [ERROR] mys_goods_tool.api | 通过短信验证码获取 login_ticket: 网络请求失败
Traceback (most recent call last):

  File "mys_goods_tool\api.py", line 853, in get_login_ticket_by_captcha

  File "mys_goods_tool\api.py", line 843, in request

  File "httpx\_client.py", line 1848, in post

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1606, in send

RuntimeError: Cannot send a request, as the client has been closed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "__init__.py", line 7, in <module>

  File "mys_goods_tool\__main__.py", line 52, in main

  File "textual\app.py", line 1233, in run

  File "asyncio\runners.py", line 190, in run

  File "asyncio\runners.py", line 118, in run

  File "asyncio\base_events.py", line 640, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run

  File "textual\message_pump.py", line 449, in _process_messages

  File "textual\message_pump.py", line 503, in _process_messages_loop

  File "textual\message_pump.py", line 566, in _dispatch_message

  File "textual\message_pump.py", line 640, in _on_message

  File "textual\_callback.py", line 74, in invoke

  File "textual\_callback.py", line 36, in _invoke

  File "mys_goods_tool\login_view.py", line 499, in _on_button_pressed

  File "mys_goods_tool\login_view.py", line 391, in login

> File "mys_goods_tool\api.py", line 850, in get_login_ticket_by_captcha

  File "tenacity\_asyncio.py", line 71, in __anext__

  File "tenacity\__init__.py", line 326, in iter

tenacity.RetryError: RetryError[<Future at 0x15fd5b39cd0 state=finished raised RuntimeError>]

**Comment by gggssepgf** [comment]
从#115 看到了解决办法
