### ISSUE TITLE
大佬帮忙看一下，获取用户ActionTicket失败，正在重试

### ISSUE THREAD

**Issue by Ljjjj-qm** [Ljzd-PRO/Mys_Goods_Tool#13]
2022-05-09 08:58:35  INFO  正在检查商品：... 的详细信息  
2022-05-09 08:58:46  INFO  正在获取用户ActionTicket  
2022-05-09 08:58:46  ERROR  Traceback (most recent call last):
  File "main.py", line 192, in __init__
TypeError: 'NoneType' object is not subscriptable
  
2022-05-09 08:58:46  ERROR  获取用户ActionTicket失败，正在重试  
2022-05-09 08:58:46  INFO  正在获取用户ActionTicket  
2022-05-09 08:58:46  ERROR  Traceback (most recent call last):
  File "main.py", line 192, in __init__
TypeError: 'NoneType' object is not subscriptable

**Comment by Ljzd-PRO** [comment]
看一下`config.ini`的`stoken`有没有填，没有填的话无法获取`ActionTicket`

**Comment by Ljjjj-qm** [comment]
可选我就没填了，现在ok了，蟹蟹哈哈
