### ISSUE TITLE
米游社账号登录失败

### ISSUE THREAD

**Issue by Yoimiya-993** [Ljzd-PRO/Mys_Goods_Tool#131]
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/52495231/939374a1-a8e8-4560-a71d-4b6a4d59be6c)
07-05 18:37:20 [INFO] mys_goods_tool.geetest | HTTP服务器 - 运行于 ('127.0.0.1', 10928) 的服务器已停止
07-05 18:37:53 [ERROR] mys_goods_tool.api | 通过短信验证码获取 login_ticket: 网络请求失败
Traceback (most recent call last):

  File "mys_goods_tool\api.py", line 853, in get_login_ticket_by_captcha

  File "mys_goods_tool\api.py", line 843, in request

  File "httpx\_client.py", line 1848, in post

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1606, in send

RuntimeError: Cannot send a request, as the client has been closed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "__init__.py", line 7, in <module>

  File "mys_goods_tool\__main__.py", line 52, in main

  File "textual\app.py", line 1233, in run

  File "asyncio\runners.py", line 190, in run

  File "asyncio\runners.py", line 118, in run

  File "asyncio\base_events.py", line 640, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run

  File "textual\message_pump.py", line 449, in _process_messages

  File "textual\message_pump.py", line 503, in _process_messages_loop

  File "textual\message_pump.py", line 566, in _dispatch_message

  File "textual\message_pump.py", line 640, in _on_message

  File "textual\_callback.py", line 74, in invoke

  File "textual\_callback.py", line 36, in _invoke

  File "mys_goods_tool\login_view.py", line 499, in _on_button_pressed

  File "mys_goods_tool\login_view.py", line 391, in login

> File "mys_goods_tool\api.py", line 850, in get_login_ticket_by_captcha

  File "tenacity\_asyncio.py", line 71, in __anext__

  File "tenacity\__init__.py", line 326, in iter

tenacity.RetryError: RetryError[<Future at 0x1e90362fbd0 state=finished raised RuntimeError>]

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/5465110615
应该修复好了，可以试一下。

**Comment by Yoimiya-993** [comment]
好的
