### ISSUE TITLE
v2.1.0没法登录

### ISSUE THREAD

**Issue by tjzq** [Ljzd-PRO/Mys_Goods_Tool#146]
version: 2.1.0
os: win10
启动程序后输入手机号点击发送验证码后并不会发送验证码，我试着用pc访问[米游社-原神](https://www.miyoushe.com/ys/)发送验证码然后去程序里输入验证码登录，发现依然不能登录。能否像V1.x版本那样设置token就行

**Comment by tjzq** [comment]
下面是日志:
07-22 18:20:12 [ERROR] mys_goods_tool.api | 获取短信验证-人机验证任务(create_mmt) - 请求失败
Traceback (most recent call last):

  File "mys_goods_tool\api.py", line 719, in create_mmt

  File "mys_goods_tool\api.py", line 712, in request

  File "httpx\_client.py", line 1757, in get

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1606, in send

RuntimeError: Cannot send a request, as the client has been closed.


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "__init__.py", line 7, in <module>

  File "mys_goods_tool\__main__.py", line 52, in main

  File "textual\app.py", line 1233, in run

  File "asyncio\runners.py", line 190, in run

  File "asyncio\runners.py", line 118, in run

  File "asyncio\base_events.py", line 640, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run

  File "textual\message_pump.py", line 449, in _process_messages

  File "textual\message_pump.py", line 503, in _process_messages_loop

  File "textual\message_pump.py", line 566, in _dispatch_message

  File "textual\message_pump.py", line 640, in _on_message

  File "textual\_callback.py", line 74, in invoke

  File "textual\_callback.py", line 36, in _invoke

  File "mys_goods_tool\login_view.py", line 303, in _on_button_pressed

  File "mys_goods_tool\login_view.py", line 283, in create_captcha

> File "mys_goods_tool\api.py", line 716, in create_mmt

  File "tenacity\_asyncio.py", line 71, in __anext__

  File "tenacity\__init__.py", line 326, in iter

tenacity.RetryError: RetryError[<Future at 0x2a52466bd90 state=finished raised RuntimeError>]
07-22 18:21:07 [INFO] mys_goods_tool.api | 通过短信验证码获取 login_ticket - 验证码错误，但你可以再次尝试登录
07-22 18:21:15 [INFO] mys_goods_tool.api | 通过短信验证码获取 login_ticket - 验证码错误，但你可以再次尝试登录
07-22 18:21:58 [INFO] mys_goods_tool.api | 通过短信验证码获取 login_ticket - 验证码错误，但你可以再次尝试登录
07-22 18:22:41 [ERROR] mys_goods_tool.api | 获取短信验证-人机验证任务(create_mmt) - 请求失败
Traceback (most recent call last):

  File "mys_goods_tool\api.py", line 719, in create_mmt

  File "mys_goods_tool\api.py", line 712, in request

  File "httpx\_client.py", line 1757, in get

  File "httpx\_client.py", line 1530, in request

  File "httpx\_client.py", line 1606, in send

RuntimeError: Cannot send a request, as the client has been closed.


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "__init__.py", line 7, in <module>

  File "mys_goods_tool\__main__.py", line 52, in main

  File "textual\app.py", line 1233, in run

  File "asyncio\runners.py", line 190, in run

  File "asyncio\runners.py", line 118, in run

  File "asyncio\base_events.py", line 640, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run

  File "textual\message_pump.py", line 449, in _process_messages

  File "textual\message_pump.py", line 503, in _process_messages_loop

  File "textual\message_pump.py", line 566, in _dispatch_message

  File "textual\message_pump.py", line 640, in _on_message

  File "textual\_callback.py", line 74, in invoke

  File "textual\_callback.py", line 36, in _invoke

  File "mys_goods_tool\login_view.py", line 303, in _on_button_pressed

  File "mys_goods_tool\login_view.py", line 283, in create_captcha

> File "mys_goods_tool\api.py", line 716, in create_mmt

  File "tenacity\_asyncio.py", line 71, in __anext__

  File "tenacity\__init__.py", line 326, in iter

tenacity.RetryError: RetryError[<Future at 0x2a524b48ed0 state=finished raised RuntimeError>]
07-22 18:24:51 [INFO] mys_goods_tool.api | 通过短信验证码获取 login_ticket - 验证码错误，但你可以再次尝试登录

**Comment by Ljzd-PRO** [comment]
这个情况和之前出现的登录时网络错误有点像

**Comment by Ljzd-PRO** [comment]
手动设置Cookies也是可以，不过比较麻烦

**Comment by Coolerds** [comment]
我好像在讨论区看到过，解决办法是先在验证码处输入随便的6位数字，再填写手机号获取验证码，多试几次就成功了。

**Comment by Coolerds** [comment]
在这个看到的#115 不知道是不是玄学还是多试几次的问题

**Comment by YuziYYDS** [comment]
开梯子了吗？
