### ISSUE TITLE
2.1.0无法兑换

### ISSUE THREAD

**Issue by add199** [Ljzd-PRO/Mys_Goods_Tool#156]
这问题是出在哪？就想换点原石，手机也没抢到...
![QQ截图20230802191838](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/114581736/bd386ac9-df35-46de-b057-806160f71417)
![QQ截图20230802191901](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/114581736/34ecd03c-6236-4275-a8d1-9a14f9b45ec1)

**Comment by qwqzz** [comment]
150原石据说两秒就没了，我60原石第4秒才成功，还是靠运气

**Comment by TianXiaSky** [comment]
连续两个星期都没兑换成功

08-04 18:00:00 [INFO] mys_goods_tool.api | 米游币商品兑换: 用户 282472561 商品 2023071811559 兑换失败，可以自行确认 - 请求发送时间: 1691143200.0910451
08-04 18:00:00 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
08-04 18:00:00 [INFO] mys_goods_tool.api | 米游币商品兑换: 用户 282472561 商品 2023071811559 兑换失败，可以自行确认 - 请求发送时间: 1691143200.1028063
08-04 18:00:00 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
08-04 18:00:00 [INFO] mys_goods_tool.api | 米游币商品兑换: 用户 282472561 商品 2023071811559 兑换失败，可以自行确认 - 请求发送时间: 1691143200.6149921
08-04 18:00:00 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
08-04 18:00:00 [INFO] mys_goods_tool.api | 米游币商品兑换: 用户 282472561 商品 2023071811559 兑换失败，可以自行确认 - 请求发送时间: 1691143200.6032004
08-04 18:00:00 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
08-04 18:00:01 [INFO] mys_goods_tool.api | 米游币商品兑换: 用户 282472561 商品 2023071811559 兑换失败，可以自行确认 - 请求发送时间: 1691143201.117539
08-04 18:00:01 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
08-04 18:00:01 [INFO] mys_goods_tool.api | 米游币商品兑换: 用户 282472561 商品 2023071811559 兑换失败，可以自行确认 - 请求发送时间: 1691143201.2286413
08-04 18:00:01 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
08-04 18:00:01 [INFO] mys_goods_tool.api | 米游币商品兑换: 用户 282472561 商品 2023071811559 兑换失败，可以自行确认 - 请求发送时间: 1691143201.4742012
08-04 18:00:01 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
08-04 18:00:02 [INFO] mys_goods_tool.api | 米游币商品兑换: 用户 282472561 商品 2023071811559 兑换失败，可以自行确认 - 请求发送时间: 1691143201.7673364
08-04 18:00:02 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
08-04 18:00:02 [INFO] mys_goods_tool.api | 米游币商品兑换: 用户 282472561 商品 2023071811559 兑换失败，可以自行确认 - 请求发送时间: 1691143202.1105556
08-04 18:00:02 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
08-04 18:00:02 [INFO] mys_goods_tool.api | 米游币商品兑换: 用户 282472561 商品 2023071811559 兑换失败，可以自行确认 - 请求发送时间: 1691143202.4392223
08-04 18:00:02 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
08-04 18:00:02 [ERROR] mys_goods_tool.api | 米游币商品兑换: 用户 282472561 商品 2023071811559 请求失败 - 请求发送时间: 1691143202.5665054
Traceback (most recent call last):

  File "threading.py", line 995, in _bootstrap

  File "threading.py", line 1038, in _bootstrap_inner

  File "threading.py", line 975, in run

  File "concurrent\futures\thread.py", line 83, in _worker

  File "concurrent\futures\thread.py", line 58, in run

  File "apscheduler\executors\base.py", line 125, in run_job

  File "mys_goods_tool\exchange_mode.py", line 106, in exchange_begin

> File "mys_goods_tool\api.py", line 1335, in good_exchange_sync

  File "httpx\_models.py", line 756, in json

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
08-04 18:00:03 [INFO] mys_goods_tool.api | 米游币商品兑换: 用户 282472561 商品 2023071811559 兑换失败，可以自行确认 - 请求发送时间: 1691143202.971081
08-04 18:00:03 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
08-04 18:00:03 [INFO] mys_goods_tool.api | 米游币商品兑换: 用户 282472561 商品 2023071811559 兑换失败，可以自行确认 - 请求发送时间: 1691143203.0904355

**Comment by Yoimiya-993** [comment]
> 150原石据说两秒就没了，我60原石第4秒才成功，还是靠运气

60是脚本抢成功的吗？

**Comment by qwqzz** [comment]
> > 150原石据说两秒就没了，我60原石第4秒才成功，还是靠运气
> 
> 60是脚本抢成功的吗？

是脚本抢的，五天前发的那个脚本

**Comment by Yoimiya-993** [comment]
> > > 150原石据说两秒就没了，我60原石第4秒才成功，还是靠运气
> > 
> > 
> > 60是脚本抢成功的吗？
> 
> 是脚本抢的，五天前发的那个脚本

那就是看运气了

**Comment by kuronekoda** [comment]
刚刚米游社大别野商品鼠标垫可以抢，但是原神和崩铁抢不了一直1028
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/136661812/1a17381c-71d5-48a7-b325-bb8c8bc06daa)
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/136661812/acd44323-973f-48d2-b9bb-5d4e63b6ebb3)
![834f254b7f0d132532f30c04e6769079_720](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/136661812/cb43b1b6-f7e2-4329-bbd4-e0abd55b74de)

**Comment by daidaidayouxia** [comment]
脚本一直兑换失败，手抢系统繁忙怎么破？
