### ISSUE TITLE
登录并一键获取Cookie提示：Pyperclip could not find a copy/paste mechanism for your system

### ISSUE THREAD

**Issue by ytgo** [Ljzd-PRO/Mys_Goods_Tool#80]
请进行以下操作：
> 1. 进入 https://user.mihoyo.com/#/login/captcha
Traceback (most recent call last):
  File "/ql/data/scripts/Mys_Goods_Tool/tool.py", line 943, in <module>
    onekey_cookie()
  File "/ql/data/scripts/Mys_Goods_Tool/tool.py", line 784, in onekey_cookie
    pyperclip.copy(url)
  File "/usr/local/lib/python3.10/site-packages/pyperclip/__init__.py", line 659, in lazy_load_stub_copy
    return copy(text)
  File "/usr/local/lib/python3.10/site-packages/pyperclip/__init__.py", line 336, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error

**Comment by Ljzd-PRO** [comment]
和剪切板有关，已经改好了。
https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/4574713068
里面有可执行文件

**Comment by ytgo** [comment]
我运行环境有问题？  还是报错

请进行以下操作：
> 1. 进入 https://user.mihoyo.com/#/login/captcha
Traceback (most recent call last):
  File "/home/ytao/Mys_Goods_Tool/tool.py", line 788, in onekey_cookie
    pyperclip.copy(command)
NameError: name 'command' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ytao/Mys_Goods_Tool/tool.py", line 949, in <module>
    onekey_cookie()
  File "/home/ytao/Mys_Goods_Tool/tool.py", line 789, in onekey_cookie
    except PyperclipException:
NameError: name 'PyperclipException' is not defined

**Comment by Ljzd-PRO** [comment]
之前用手机改的，疏忽了，现在应该可以了😂
pyperclip不能用应可能是系统是纯命令行 无图形界面的，不存在剪切板，也就不能拷贝到剪切板。
https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/4583909169

**Comment by ytgo** [comment]
> 4. 在此输入验证码 - 用于获取login_ticket (不会发送给任何第三方服务器，项目开源安全):
> 798130                                                          正在登录...
正在获取stoken...
> 5. 刷新页面，再次进入 https://user.mihoyo.com/#/login/captcha
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Mys_Goods_Tool/tool.py", line 950, in <module>
    onekey_cookie()                                                 File "/data/data/com.termux/files/home/Mys_Goods_Tool/tool.py", line 856, in onekey_cookie
    pyperclip.copy(url)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyperclip/__init__.py", line 336, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException:                                         Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error


又出现同样问题了

**Comment by Ljzd-PRO** [comment]
暂时删除了拷贝至剪切板的功能。发布了新版本 https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/tag/v1.4.5
